In [13]:
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [34]:
l = 100
inputs = np.random.normal(loc=0, scale=2, size=(100,4))
weight = np.array([[1,0,1], [1,-1,0], [0,0,1], [1,0,0] ])
bias = np.array([-1,1,1])

gens = np.matmul(inputs,weight) + bias
np.shape(gens)

(100, 3)

In [27]:
model = LinearRegression()
model.fit(inputs, gens)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [81]:
W = model.coef_
R= W
np.shape(W)
R = np.abs(W)

In [50]:
np.sum(W, axis=0) #axis= 0 scorre su righe, axis=1 scorre su colonne

array([3.0000000e+00, 4.4408921e-16, 2.0000000e+00])

generative $K=3$, latent $D=4$ 

In [84]:
R_g =  np.sum(R, axis=0)
R_g

array([3., 2., 2.])

In [85]:
P = np.zeros(shape=np.shape(W))

In [87]:
for i in range(len(P)):
    for j in range(  len(P[0] )):
        ########################
        P[i,j] = R[i,j]/R_g[j]

In [88]:
H_D = np.zeros(shape=(3,))
for j in range(3):
    H_D[j] = -np.sum(P[:,j]*np.log(P[:,j] +10**-4 ) )

In [90]:
H_D /= np.log(4)
H_D

array([0.57149831, 0.3605697 , 0.3605697 ])

In [91]:
1- H_D

array([0.42850169, 0.6394303 , 0.6394303 ])

In [78]:
P[:,1]

array([2.25179981e+15, 2.25179981e+15, 2.50000000e-01, 2.50000000e-01])

In [99]:
rho = np.zeros(3)

R_tot = np.sum(R)    
rho = np.sum(R, axis=0)/R_tot

In [100]:
R_tot

7.000000000000003

In [101]:
rho

array([0.42857143, 0.28571429, 0.28571429])

In [103]:
D = np.dot(1-H_D, rho)

In [104]:
D

0.5490323248907051

In [145]:
def Interpretability(z,g, rel_factors=10**4):
    
    D = len(z[0])
    K = len(g[0])
    
    model = LinearRegression()
    model.fit(z,g)
    
    R = np.abs( model.coef_ )
    
    R_g = np.sum(R, axis=0)
    
    P = np.zeros(np.shape(R))
    for i in range(K):
        for j in range(D):
            P[i,j] = R[i,j]/(R_g[j]+10**-5)
    
    H_D = np.zeros(K)
    for j in range(K):
        H_D[j] = - np.sum( P[:,j] * np.log(P[:,j]+ 10**-5) ) 
    
    I = 1 - H_D/np.log(D)
    
    rho = np.sum(R, axis=1)/np.sum(R)
    
    I_tot = np.sum(rho*I)
    
    return I, I_tot

In [186]:
g = np.random.uniform(0,2, size=(100,2) )
W = np.array( [[1, 2], [1,1]]   )
z = np.matmul(g,W)

In [187]:
I, I_tot = Interpretability(z,g)

In [188]:
I

array([8.17312715e-02, 2.66401662e-05])

In [189]:
I_tot

0.03270849271499123