In [1]:
import torch
import numpy as np

In [6]:
torch.rand(10)

tensor([0.0951, 0.5755, 0.9443, 0.3994, 0.6150, 0.2281, 0.7349, 0.9077, 0.5992,
        0.6392])

In [5]:
m = torch.nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)


In [4]:
output

tensor([[0.2160, 0.4536, 0.3303],
        [0.4582, 0.2023, 0.3395]])

In [5]:
input

tensor([[ 0.6459,  1.3876,  1.0705],
        [ 0.3537, -0.4641,  0.0537]])

In [2]:
loss = torch.nn.BCELoss(reduction='mean')

In [12]:
x = torch.rand(size=(10,3) )
y = torch.rand(size=(10,3))

In [16]:
print(loss(x,y))

l = 0
for i in range(3):
    prev = loss(x[:,i], y[:,i])
    print(prev)
    l += prev/3
    
l

tensor(0.9372)
tensor(1.2814)
tensor(0.8669)
tensor(0.6633)


tensor(0.9372)

In [18]:
h = torch.rand(size=(10,5))
torch.sigmoid(h )

tensor([[0.5026, 0.5630, 0.5479, 0.6246, 0.7307],
        [0.6678, 0.5823, 0.6452, 0.6877, 0.5414],
        [0.6222, 0.6543, 0.6982, 0.5648, 0.6570],
        [0.6215, 0.6958, 0.6939, 0.6531, 0.6072],
        [0.6554, 0.6808, 0.6874, 0.6534, 0.6405],
        [0.6139, 0.6622, 0.6285, 0.7252, 0.5282],
        [0.5588, 0.5836, 0.5466, 0.6389, 0.6521],
        [0.5894, 0.6339, 0.5705, 0.6177, 0.7097],
        [0.6496, 0.5977, 0.6661, 0.5161, 0.7184],
        [0.7090, 0.6626, 0.7261, 0.7120, 0.5878]])