In [36]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [2]:
import torch

In [8]:
torch.nn.functional.one_hot(torch.randint(3,size=(10,)))

tensor([[0, 0, 1],
        [0, 0, 1],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 1],
        [0, 0, 1],
        [0, 0, 1],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 1]])

In [10]:
torch.cat((torch.randint(3,(10,)), torch.randn(10)) )

tensor([ 1.0000,  2.0000,  1.0000,  0.0000,  0.0000,  2.0000,  0.0000,  0.0000,
         0.0000,  0.0000, -0.2732, -0.6458,  1.2326, -0.3878, -0.3026, -0.8986,
        -1.0153, -0.8249,  0.1790,  1.5087])

In [11]:
torch.nn.functional.one_hot(torch.randint(3,size=(10,)),num_classes=5 )

tensor([[0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0]])

In [23]:
### HOW TO STACK THEM TOGETHER

data = torch.zeros((10,10))

data[0,:] = torch.randint(0,3,(10,) )

data = data.t()

classes = torch.nn.functional.one_hot(data[:,0].to(dtype=torch.long), num_classes=3 )


for i in range(len(data)):
    data[i,0] 
    pass

In [33]:
data_new = torch.hstack((classes, data[:,1:]), )

In [59]:
a = np.array([0,1,2,1,1,1])
b = np.zeros((a.size, a.max()+1))
b[np.arange(a.size),a] = 1

In [60]:
N = 10
data = np.zeros((N,5))
data[:,0] = np.random.randint(0,3,10)

In [70]:
values = np.asarray(data[:,0], dtype=np.int)
b = np.zeros((len(data), 3))
b[np.arange(len(data)),values] = 1

In [89]:
data_new = np.hstack((b, data[:,1:]))
np.shape(data_new)

(10, 7)

In [84]:
x = np.array([1,1000,1,3,2,1,2])

x[[0,2,3,4,]]

array([1, 1, 3, 2])